name: PyInstaller Build

on:
  push:
    branches:
      - main  # Adjust as needed
  workflow_dispatch:  # Added for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Add other dependencies from your requirements.txt if available
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean ainterface.exe.spec.template  # Updated to reference the template file

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ainterface-exe
          path: dist/ainterface.exe  # Assuming the output is in dist/ folder